module.exports = {
  content: [
    // ... your content sources
  ],
  theme: {
    extend: {
      colors: {
        nord: {
          'polar-night-1': '#2E3440',
          'polar-night-2': '#3B4252',
          'polar-night-3': '#434C5E',
          'polar-night-4': '#4C566A',
          'snow-storm-1': '#D8DEE9',
          'snow-storm-2': '#E5E9F0',
          'snow-storm-3': '#ECEFF4',
          'frost-1': '#8FBCBB',
          'frost-2': '#88C0D0',
          'frost-3': '#81A1C1',
          'frost-4': '#5E81AC',
          'aurora-red': '#BF616A',
          'aurora-orange': '#D08770',
          'aurora-yellow': '#EBCB8B',
          'aurora-green': '#A3BE8C',
          'aurora-purple': '#B48EAD',
        },
        solarized: {
          'base03': '#002b36',
          'base02': '#073642',
          'base01': '#586e75',
          'base00': '#657b83',
          'base0': '#839496',
          'base1': '#93a1a1',
          'base2': '#eee8d5',
          'base3': '#fdf6e3',
          'yellow': '#b58900',
          'orange': '#cb4b16',
          'red': '#dc322f',
          'magenta': '#d33682',
          'violet': '#6c71c4',
          'blue': '#268bd2',
          'cyan': '#2aa198',
          'green': '#859900',
        },
        'bg-primary': 'var(--bg-primary)',
        'bg-secondary': 'var(--bg-secondary)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'accent': 'var(--accent)',
        'accent-hover': 'var(--accent-hover)',
      },
    },
  },
  plugins: [],
}
